[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 15

[font.bold]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9
