[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
# shape = "Beam"

[font]
size = 13

[font.bold]
family = "Fira Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.85

[window.padding]
x = 12
y = 12
