[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
# shape = "Beam"

[font]
size = 14

[font.normal]
family = "Iosevka"
style = "Regular"

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[terminal.shell]
program = "/usr/bin/bash"
# args = [ "new-session", "-A", "-D", "-s", "main" ]

[env]												# Fixes tmux colors
TERM = "xterm-256color"

[window]
opacity = 0.85

[window.padding]
x = 12
y = 12

[terminal]
