[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
# shape = "Beam"

[font]
size = 13

[font.bold]
family = "Blex Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Blex Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Blex Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Mono Nerd Font"
style = "Regular"

# [terminal.shell]
# program = "/usr/bin/tmux"
# args = [ "new-session", "-A", "-D", "-s", "main" ]
[env]
TERM = "xterm-256color"

[window]
opacity = 0.85

[window.padding]
x = 12
y = 12

[terminal]
