[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
# shape = "Beam"

[font]
size = 14

[font.normal]
family = "Aporetic Sans Mono"
style = "Regular"

[font.bold]
family = "Aporetic Sans Mono"
style = "Regular"

[font.bold_italic]
family = "Aporetic Sans Mono"
style = "Italic"

[font.italic]
family = "Aporetic Sans Mono"
style = "Italic"

[env]												# Fixes tmux colors
TERM = "xterm-256color"

[window]
opacity = 0.7

[window.padding]
x = 12
y = 12

[terminal]
